name: Xamarin.SwiftUI.0.2.${{ env.BuildID }}-pre

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  DebugBuildAndTest:
    name: Debug Build and Test

    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout current repo
        uses: actions/checkout@v2
      
      # Ensure we have .NET 5 and 6 installed
      - name: Setup .NET Core SDK 5.0.x and 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x
